### ISSUE TITLE
"To Farm" icon does not show up with new checkbox options

### ISSUE THREAD

**Issue by bgarrison25** [lyrgard/ffbeEquip#187]
When selecting one of the new checkboxes for including easy to farm items or chocobo den items, if they find an item and add it to a build it does not have the "to farm" flag added to it. See attached screenshot

![image](https://user-images.githubusercontent.com/2955550/44541778-ffd38880-a6d8-11e8-9693-250a43ef48e0.png)

**Comment by lyrgard** [comment]
@biovenger Do you want to take a look at it ?

**Comment by tomurderthelight** [comment]
this reminds me of the issue that was fixed with farmable TMs. the first copy of the not-owned item would not be flagged for farming, but the second not-owned copy on the same unit would be. it also caused some false flagging of owned items, iirc, when equipping owned and not-owned items at the same time. could this be a similar issue?

**Comment by Darwe-Canine** [comment]
Still an issue, not sure what the correct icon would be to indicate chocobo vs store vs quest etc, or just use the current "need to farm" icon with mouseover text indicating where it can be aquired (or just quest vs chocobo vs whatever).
