### ISSUE TITLE
unit page bugs. limited 7\*. 5\* owned to not-owned.

### ISSUE THREAD

**Issue by tomurderthelight** [lyrgard/ffbeEquip#214]
there are a few bugs with converting limited units to 7\*.

unit counts, 1:
limited time 7\* units are counted as non-limited units.

unit counts, 2:
after adding limited 7\* units, each time the page is refreshed the non-limited 7\* unit count increases by at least 1. 
removing the limited units will cause the non-limited count to reset to the correct number.

these two are probably related, and caused by the limited unit count being added to the wrong variable.

unit images and 0 quantities:
after converting a unit from 5\* to 7\*, if the 5\* unit's quantities are reduced to 0 the unit does not dim/fade back to the not-owned display setting.

**Comment by tomurderthelight** [comment]
adding a note in regards to "unit images and 0 quantities":
this carries over to the unit search page in that the affected units still show up in searches using the option to "only show owned units".

**Comment by tomurderthelight** [comment]
more on 0 quantity units.

the "owned" flag is not being properly reset after units are converted to 7\* IF their "farmable tmr" quantity is not reduced to 0 before the unit quantity is reduced to 0, except when using the 7\* conversion function.

example/reproduction:
unit: Lightning (any that can be converted to 7\*)
5\* unit quantity: 2
farmable tmr: 2
convert to 7\*.
7\* unit quantity: 1
5\* unit quantity: 0
farmable tmr: 2
reduce farmable tmr to 0.
5\* unit remains highlighted as if still owned, though both quantities are 0.

possible user ability to correct:
set 5\* unit quantity to 1
reduce farmable tmr quantity to 0
reduce 5\* unit quantity to 0
owned flag should now reset to 'not owned'.

using this method creates a new problem, however:
resetting the 'owned' flag of the 5\* unit removes the 7\* unit, regardless of 7\* unit quantity.

---

reproduction of the 7\* limited units counts bug is easy to reproduce:
note unit counts.
add 4 5\* dragonlords (any time limited 5\*)
convert to 2 7\*.
wait for everything to save.
reload page.
check unit counts against previous notation.

**Comment by mkujawa** [comment]
Further related strangeness:
I have 1 Marquis de Leon.  I have 12 unique 7*s and one dupe.  I see:

> All Units
> 13 / 56 (14)
> 
> Non-limited units
> 13 / 56 (14)
> 

What I should see is:

> All Units
> 11 / 46 (12)
>
> Non-limited units
> 1 / 5 (1)

**Comment by lyrgard** [comment]
Should be corrected now !

**Comment by tomurderthelight** [comment]
unit counts appear to be corrected. still have some small issues here.

1. unit counts do not immediately update when converting 5\* to 7\*. it is delayed until another unit is added or the page is refreshed, whichever happens first.

2. 7\* units are removed from inventory when their 5\* icon is dimmed. let me know if you want a separate issue created for this.

for reproduction of both:
1: pick a 5\*-7\* unit that you do not own, doesn't matter if it is limited or not. use the same unit for steps 2 and 4.
2: add 2 quantity, note counts.
3: convert to 7*, note counts. 7\* should not be shown as added.
4: add 1 5\*, note counts. 7\* should now be shown as added.
5: reduce 5\* tmr to farm to 0.
6: reduce 5\* unit quantity to 0.
7: note that 7\* still appears to be there.
8: reload page, note that 7\* is missing.
